version: 2
jobs:
  save_document:
    docker:
      - image: circleci/ruby:2.4.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - store_artifacts:
          path: ~/project/docs
workflows:
  version: 2
  save_doc:
    jobs:
      - save_document
